name: string-function

on: push

jobs:
  string-function:
    runs-on: ubuntu-latest
    steps:
      - name: startswith git
        if: startsWith('github actions', 'git')
        run: echo 'git'
      
      - name: startswith test
        if: startsWith('github actions', 'git')
        run: echo 'git'
      
      - name: endswith ions
        if: endsWith('github actions', 'git')
        run: echo 'git'
      
      - name: endswith test
        if: endsWith('github actions', 'git')
        run: echo 'git'